#!/usr/bin/env python3
"""Compute paired McNemar exact tests for every (arm_i, arm_j) pair.

Inputs:  results/*_per_question.jsonl
Output:  reports/02_paired_asha_vs_gemini.md  (focused on Asha vs Gemini)
        and writes a full pairwise CSV: reports/02_pairwise_matrix.csv
"""
from __future__ import annotations

import json
import math
from math import comb
from pathlib import Path
from itertools import combinations

ARMS = ["asha", "opus45", "o4mini", "gemini", "gpt4o"]
LABELS = {
    "asha":   "Asha",
    "opus45": "Claude Opus 4.5",
    "o4mini": "OpenAI o4-mini-high",
    "gemini": "Gemini 3.1 Pro Preview",
    "gpt4o":  "GPT-4o",
}


def mcnemar_exact_two_sided(b: int, c: int) -> float:
    n = b + c
    if n == 0:
        return 1.0
    p = 0.5
    pmf = [comb(n, i) * (p ** i) * ((1 - p) ** (n - i)) for i in range(n + 1)]
    low, hi = min(b, c), max(b, c)
    return sum(pi for i, pi in enumerate(pmf) if i <= low or i >= hi)


def or_with_ci(b: int, c: int) -> tuple[float, float, float]:
    if b == 0 or c == 0:
        return (float('inf'), 0.0, float('inf'))
    or_ = b / c
    se = math.sqrt(1 / b + 1 / c)
    return (or_, or_ * math.exp(-1.96 * se), or_ * math.exp(1.96 * se))


def load_arm(results_dir: Path, arm: str) -> dict[str, bool]:
    fp = results_dir / f"{arm}_per_question.jsonl"
    out = {}
    for L in fp.read_text().splitlines():
        if not L.strip():
            continue
        r = json.loads(L)
        out[r["qid"]] = bool(r.get("correct"))
    return out


def main() -> None:
    here = Path(__file__).resolve().parent.parent
    results_dir = here / "results"
    reports = here / "reports"
    reports.mkdir(exist_ok=True)

    arm_data = {arm: load_arm(results_dir, arm) for arm in ARMS}
    common = set.intersection(*[set(d.keys()) for d in arm_data.values()])
    common = sorted(common)

    asha_md = [
        "# MedQA 2026-05-04 — Paired McNemar: Asha vs Bare Gemini 3.1 Pro\n",
        "Generated by `scripts/mcnemar_paired_lift.py`.\n",
        "",
        "**Asha's verbalization layer is gravity-routed Vertex Gemini.** "
        "Holding the underlying LM family constant, this paired test measures "
        "the incremental contribution of Asha's KIL retrieval + Resolve(P) "
        "cognition pipeline on top of the bare 100%-Pro Gemini arm.\n",
        "",
        "| Cell | Definition | Count |",
        "|------|------------|------:|",
    ]

    a = b = c = d = 0
    for q in common:
        ar = arm_data["asha"][q]
        pr = arm_data["gemini"][q]
        if ar and pr:     a += 1
        elif ar:          b += 1
        elif pr:          c += 1
        else:             d += 1
    n = a + b + c + d
    p_val = mcnemar_exact_two_sided(b, c)
    or_, lo, hi = or_with_ci(b, c)

    asha_md += [
        f"| a | both right | {a} |",
        f"| b | Asha right, Gemini wrong | {b} |",
        f"| c | Asha wrong, Gemini right | {c} |",
        f"| d | both wrong | {d} |",
        f"| n | total paired | {n} |",
        "",
        f"- **Paired lift (b−c)/n: {(b-c)/n*100:+.2f} pp**",
        f"- **McNemar exact two-sided p = {p_val:.2e}**",
        f"- Odds ratio (b/c) = {or_:.2f}, 95% CI [{lo:.2f}, {hi:.2f}]",
        f"- Rescue rate (b / (b+d)) = {b}/{b+d} = {b/(b+d)*100:.1f}% of Gemini's misses",
        f"- Regression rate (c / (a+c)) = {c}/{a+c} = {c/(a+c)*100:.2f}% of Gemini's successes",
        "",
        "## Reproduction",
        "```",
        "python3 scripts/mcnemar_paired_lift.py",
        "```",
    ]
    (reports / "02_paired_asha_vs_gemini.md").write_text("\n".join(asha_md))

    csv_lines = ["arm_i,arm_j,a,b,c,d,n,lift_pp,p_value,OR,OR_lo,OR_hi"]
    for i, j in combinations(ARMS, 2):
        ai = arm_data[i]
        aj = arm_data[j]
        aa = bb = cc = dd = 0
        for q in common:
            ri, rj = ai[q], aj[q]
            if ri and rj:   aa += 1
            elif ri:        bb += 1
            elif rj:        cc += 1
            else:           dd += 1
        nn = aa + bb + cc + dd
        pv = mcnemar_exact_two_sided(bb, cc)
        oor, lo2, hi2 = or_with_ci(bb, cc)
        csv_lines.append(
            f"{i},{j},{aa},{bb},{cc},{dd},{nn},{(bb-cc)/nn*100:+.2f},"
            f"{pv:.4g},{oor:.3g},{lo2:.3g},{hi2:.3g}"
        )
    (reports / "02_pairwise_matrix.csv").write_text("\n".join(csv_lines) + "\n")
    print(f"Asha vs Gemini: lift={b-c}/{n} = +{(b-c)/n*100:.2f} pp, p={p_val:.2e}, OR={or_:.2f} [{lo:.2f}, {hi:.2f}]")
    print(f"wrote: {reports / '02_paired_asha_vs_gemini.md'}")
    print(f"wrote: {reports / '02_pairwise_matrix.csv'}")


if __name__ == "__main__":
    main()
