#!/usr/bin/env python3
"""Wrong-letter independence test (parser-conditioned).

The 2026-05-04 preliminary YC narrative claimed "Asha's errors are
statistically INDEPENDENT of bare Gemini's parametric prior", citing 11/32 =
34.4% same-letter agreement on the both-wrong subset against H0=1/3.

That claim is overturned. Of the 32 both-wrong cells, only 12 have BOTH arms
emitting a parseable wrong letter; the other 20 are "Gemini unparseable + Asha
parsed-wrong" and cannot share a letter. On the correctly-conditioned n=12,
the same-letter agreement is 11/12 = 91.7%, two-sided exact binomial p<0.0001
against H0=1/3 — the errors are STRONGLY CORRELATED, not independent.

This script reproduces both numbers (correct + the original misconditioned
one) so the retraction is auditable.

Output: reports/03_wrong_letter_test.md
"""
from __future__ import annotations

import json
import math
from math import comb
from pathlib import Path


def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1.0 + z * z / n
    center = p + z * z / (2 * n)
    margin = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return ((center - margin) / denom, (center + margin) / denom)


def binom_two_sided(k: int, n: int, p0: float) -> float:
    if n == 0:
        return 1.0
    pmf = [comb(n, i) * (p0 ** i) * ((1 - p0) ** (n - i)) for i in range(n + 1)]
    p_obs = pmf[k]
    return min(1.0, sum(pi for pi in pmf if pi <= p_obs + 1e-15))


def main() -> None:
    here = Path(__file__).resolve().parent.parent
    results_dir = here / "results"

    asha = {}
    gemini = {}
    for L in (results_dir / "asha_per_question.jsonl").read_text().splitlines():
        r = json.loads(L)
        asha[r["qid"]] = (r.get("gold"), r.get("predicted"), bool(r.get("parsed")), bool(r.get("correct")))
    for L in (results_dir / "gemini_per_question.jsonl").read_text().splitlines():
        r = json.loads(L)
        gemini[r["qid"]] = (r.get("gold"), r.get("predicted"), bool(r.get("parsed")), bool(r.get("correct")))

    common = sorted(set(asha) & set(gemini))
    both_wrong = []
    both_parsed_wrong = []
    asha_wrong_gemini_unparse = 0
    asha_unparse_gemini_wrong = 0
    both_unparseable = 0
    same_letter_strict = 0

    for q in common:
        gold, a_pred, a_parsed, a_corr = asha[q]
        _, g_pred, g_parsed, g_corr = gemini[q]
        if (not a_corr) and (not g_corr):
            both_wrong.append(q)
            if a_parsed and g_parsed:
                both_parsed_wrong.append(q)
                if a_pred == g_pred:
                    same_letter_strict += 1
            elif a_parsed and not g_parsed:
                asha_wrong_gemini_unparse += 1
            elif not a_parsed and g_parsed:
                asha_unparse_gemini_wrong += 1
            else:
                both_unparseable += 1

    n_d = len(both_wrong)
    n_sub = len(both_parsed_wrong)
    rate_sub = same_letter_strict / n_sub if n_sub else 0.0
    lo_sub, hi_sub = wilson_ci(same_letter_strict, n_sub)
    p_corrected = binom_two_sided(same_letter_strict, n_sub, 1.0 / 3.0)

    same_letter_in_d = 0
    for q in both_wrong:
        _, a_pred, _, _ = asha[q]
        _, g_pred, _, _ = gemini[q]
        if a_pred and g_pred and a_pred == g_pred:
            same_letter_in_d += 1
    rate_d = same_letter_in_d / n_d if n_d else 0.0

    md = [
        "# MedQA 2026-05-04 — Wrong-letter independence test (overturned claim)\n",
        "Generated by `scripts/wrong_letter_independence.py`.\n",
        "",
        "## Retracted public claim",
        "",
        "On 2026-05-04 our preliminary YC narrative reported:",
        "> *When both arms are wrong on the same question, they pick the "
        "same wrong letter 11/32 = 34.4% of the time — H₀ for independent "
        "uniform errors predicts 33.3% (p = 1.00); Asha's errors are "
        "statistically independent of Gemini's parametric priors.*",
        "",
        "This claim is **incorrect**. The denominator (the b+d=32 'both wrong' McNemar cell) "
        "includes cases where Gemini's response was unparseable — cases where "
        "Gemini did not emit any letter and therefore cannot 'share a wrong letter' with Asha.",
        "",
        "## Correctly-conditioned test",
        "",
        f"Of the {n_d} both-wrong questions:",
        f"- {n_sub} have BOTH arms emitting a parseable wrong letter",
        f"- {asha_wrong_gemini_unparse} have Asha parsed-wrong + Gemini UNPARSEABLE",
        f"- {asha_unparse_gemini_wrong} have Asha UNPARSEABLE + Gemini parsed-wrong",
        f"- {both_unparseable} have both unparseable",
        "",
        f"On the valid sub-test (n={n_sub}):",
        f"- Same-letter agreement: **{same_letter_strict}/{n_sub} = {rate_sub*100:.1f}%**",
        f"- Wilson 95% CI: [{lo_sub*100:.1f}%, {hi_sub*100:.1f}%]",
        f"- H₀ (independent random pick among the 3 wrong letters): 1/3 ≈ 33.3%",
        f"- Two-sided exact binomial p-value: **{p_corrected:.4g}**",
        "",
        f"**Verdict: REJECT H₀.** When both Asha and Gemini emit a "
        f"parseable wrong letter, they pick the SAME wrong letter in "
        f"{same_letter_strict}/{n_sub} cases. The errors are strongly "
        f"correlated, NOT independent.",
        "",
        "## Original (misconditioned) calculation, for traceability",
        "",
        f"On the original n=d={n_d} denominator (which includes "
        f"Gemini-unparseable cases that can never share a letter), the rate is "
        f"{same_letter_in_d}/{n_d} = {rate_d*100:.1f}%. This is the number we "
        f"originally reported. It is arithmetically correct but the choice of "
        f"denominator was wrong, which inverted the conclusion.",
        "",
        "## What this means for the architecture story",
        "",
        "Asha's +3.22 pp paired lift over bare Gemini is **not** explained by "
        "Asha generating reasoning paths that are statistically independent of "
        "Gemini's parametric priors. The lift is explained by:",
        "",
        f"1. **Format-compliance rescue (META_CORRECT primitive)**: of the "
        f"66 questions where Asha is right and Gemini is wrong, ~51 are cases "
        f"where Gemini's response was unparseable and Asha's synthesis layer "
        f"recovered a structured answer.",
        "2. **Retrieval-grounded substitution**: on the remaining questions, "
        "KIL evidence steers Asha toward the correct letter even when bare "
        "Gemini would have picked a wrong one.",
        "",
        "When Asha CANNOT rescue and both arms commit to a parseable wrong "
        "letter, the synthesis layer almost always inherits Gemini's "
        f"parametric prior (same wrong letter {same_letter_strict}/{n_sub}). "
        "This is honest, useful information about how the architecture works.",
    ]
    out = here / "reports" / "03_wrong_letter_test.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(md))
    print(f"n_d={n_d}, n_sub={n_sub}, same_letter={same_letter_strict}, p={p_corrected:.4g}")
    print(f"wrote: {out}")


if __name__ == "__main__":
    main()
